name: Automatic Build

on: [push, pull_request]

jobs:
  buildForWin32:
    name: Win32 Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.45f2
        buildName: ["iOS6Simulator_Win32"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      - uses: actions/upload-artifact@v4
        with:
          name: Windows (x86)
          path: build
  buildForWin64:
    name: Win64 Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.45f2
        buildName: ["iOS6Simulator_Win64"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - uses: actions/upload-artifact@v4
        with:
          name: Windows (x86-64)
          path: build
  buildForOSX:
    name: OSX Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.45f2
        buildName: ["iOS6Simulator_MacOS"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX

      - uses: actions/upload-artifact@v4
        with:
          name: Mac OS X (x86-64)
          path: build
  buildForLinux:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.45f2
        buildName: ["iOS6Simulator_Linux"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64

      - uses: actions/upload-artifact@v4
        with:
          name: Linux (x86-64)
          path: build
